/**
 * web3JS Sample DAPP by http://acloudfan.com
 * Version: 102     May 20th, 2017
 * 
 * Application developed as part of the course on Ethereum Blockchain
 * All Rights Reserved - Please do not share. 
 * Updated versions of the code is available on the link below:
 * APP will be updated time to time so please check back
 * 
 * http://www.acloudfan.com
 * 
 * This DAPP is available on the following link .... to use it you would need MetaMask
 * http://TheDapps.com
 * 
 * Geth
 * =====
 * Application developed against Geth/ROPSTEN
 * 
 * TestRPC
 * =======
 * Some API NOT Supported in TestRPC
 * Etherscan.io links will not be supported for TestRPC
 * 
 * META MASK
 * =========
 * MetaMask will work - except some for some functions coded SYNCHRONOUSLY
 * You may change it to work with MetaMask
 * 
 */


// The sample code was compiled in Remix
// Bytecode / Interface generated by Remix was pasted here
var contract_abidefinition = '[{"constant":false,"inputs":[{"name":"amt","type":"uint256"},{"name":"name","type":"string"}],"name":"recharge","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"balance","type":"uint256"}],"name":"EventRechargeDone","type":"event"},{"constant":true,"inputs":[],"name":"getBalance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getLast1Transaction","outputs":[{"name":"amount","type":"uint256"},{"name":"name","type":"string"},{"name":"when","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getLast2Transaction","outputs":[{"name":"amount","type":"uint256"},{"name":"name","type":"string"},{"name":"when","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getLast3Transaction","outputs":[{"name":"amount","type":"uint256"},{"name":"name","type":"string"},{"name":"when","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getLast4Transaction","outputs":[{"name":"amount","type":"uint256"},{"name":"name","type":"string"},{"name":"when","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getLastTransaction","outputs":[{"name":"amount","type":"uint256"},{"name":"name","type":"string"},{"name":"when","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]';
var contract_bytecode = '0x60806040523480156200001157600080fd5b506000808190555060006001819055506200006960016040518060400160405280600781526020017f4d757374616661000000000000000000000000000000000000000000000000008152506200018f60201b60201c565b620000b160016040518060400160405280600681526020017f48757361696e00000000000000000000000000000000000000000000000000008152506200018f60201b60201c565b620000f960016040518060400160405280600681526020017f416b6874617200000000000000000000000000000000000000000000000000008152506200018f60201b60201c565b6200014160016040518060400160405280600481526020017f41726966000000000000000000000000000000000000000000000000000000008152506200018f60201b60201c565b6200018960016040518060400160405280600581526020017f46617a616c0000000000000000000000000000000000000000000000000000008152506200018f60201b60201c565b62000352565b8160008082825401925050819055508160026000600154815260200190815260200160002060000181905550806002600060015481526020019081526020016000206001019080519060200190620001e9929190620002a3565b503360026000600154815260200190815260200160002060020160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555042600260006001548152602001908152602001600020600301819055506001600081548092919060010191905055506000547f505087f5c90dd1e66c43ece502a9e408fc40efee451b05b57babb377c6cc6dc860405160405180910390a25050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f10620002e657805160ff191683800117855562000317565b8280016001018555821562000317579182015b8281111562000316578251825591602001919060010190620002f9565b5b5090506200032691906200032a565b5090565b6200034f91905b808211156200034b57600081600090555060010162000331565b5090565b90565b610b0c80620003626000396000f3fe608060405234801561001057600080fd5b506004361061007d5760003560e01c806393fe92311161005b57806393fe9231146101c25780639ed0918f14610253578063e8f4d590146102e4578063f7e03fd8146103a95761007d565b806312065fe01461008257806325acce0e146100a05780634d33c0ad14610131575b600080fd5b61008a61043a565b6040518082815260200191505060405180910390f35b6100a8610443565b6040518084815260200180602001838152602001828103825284818151815260200191508051906020019080838360005b838110156100f45780820151818401526020810190506100d9565b50505050905090810190601f1680156101215780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b61013961053e565b6040518084815260200180602001838152602001828103825284818151815260200191508051906020019080838360005b8381101561018557808201518184015260208101905061016a565b50505050905090810190601f1680156101b25780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b6101ca610639565b6040518084815260200180602001838152602001828103825284818151815260200191508051906020019080838360005b838110156102165780820151818401526020810190506101fb565b50505050905090810190601f1680156102435780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b61025b610734565b6040518084815260200180602001838152602001828103825284818151815260200191508051906020019080838360005b838110156102a757808201518184015260208101905061028c565b50505050905090810190601f1680156102d45780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b6103a7600480360360408110156102fa57600080fd5b81019080803590602001909291908035906020019064010000000081111561032157600080fd5b82018360208201111561033357600080fd5b8035906020019184600183028401116401000000008311171561035557600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929050505061082f565b005b6103b1610941565b6040518084815260200180602001838152602001828103825284818151815260200191508051906020019080838360005b838110156103fd5780820151818401526020810190506103e2565b50505050905090810190601f16801561042a5780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b60008054905090565b6000606060008060056001540390506002600082815260200190815260200160002060000154600260008381526020019081526020016000206001016002600084815260200190815260200160002060030154818054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561052b5780601f106105005761010080835404028352916020019161052b565b820191906000526020600020905b81548152906001019060200180831161050e57829003601f168201915b5050505050915093509350935050909192565b6000606060008060026001540390506002600082815260200190815260200160002060000154600260008381526020019081526020016000206001016002600084815260200190815260200160002060030154818054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156106265780601f106105fb57610100808354040283529160200191610626565b820191906000526020600020905b81548152906001019060200180831161060957829003601f168201915b5050505050915093509350935050909192565b6000606060008060036001540390506002600082815260200190815260200160002060000154600260008381526020019081526020016000206001016002600084815260200190815260200160002060030154818054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156107215780601f106106f657610100808354040283529160200191610721565b820191906000526020600020905b81548152906001019060200180831161070457829003601f168201915b5050505050915093509350935050909192565b6000606060008060046001540390506002600082815260200190815260200160002060000154600260008381526020019081526020016000206001016002600084815260200190815260200160002060030154818054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561081c5780601f106107f15761010080835404028352916020019161081c565b820191906000526020600020905b8154815290600101906020018083116107ff57829003601f168201915b5050505050915093509350935050909192565b8160008082825401925050819055508160026000600154815260200190815260200160002060000181905550806002600060015481526020019081526020016000206001019080519060200190610887929190610a3b565b503360026000600154815260200190815260200160002060020160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555042600260006001548152602001908152602001600020600301819055506001600081548092919060010191905055506000547f505087f5c90dd1e66c43ece502a9e408fc40efee451b05b57babb377c6cc6dc860405160405180910390a25050565b60006060600080600180540390506002600082815260200190815260200160002060000154600260008381526020019081526020016000206001016002600084815260200190815260200160002060030154818054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610a285780601f106109fd57610100808354040283529160200191610a28565b820191906000526020600020905b815481529060010190602001808311610a0b57829003601f168201915b5050505050915093509350935050909192565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f10610a7c57805160ff1916838001178555610aaa565b82800160010185558215610aaa579182015b82811115610aa9578251825591602001919060010190610a8e565b5b509050610ab79190610abb565b5090565b610add91905b80821115610ad9576000816000905550600101610ac1565b5090565b9056fea165627a7a723058208f168568e57250c9466484a86d8ab44e77ff87797123f0e49ee26342f12c4d630029';
var contract_address = '0x2080ad28faf2cd26b335ad2562912c2bd4339496';

var autoRetrieveFlag = true;

// Holds the accounts
var accounts;
var gauge;

// Holds the filter objects
var filterWatch;
var filterEventCounter;

// Holds the contract event object
var contractEvent;
var contractEventCounter = 0;

// Maintains the info on node type
var nodeType = 'metamask';

/**
 * Listener for load
 */
window.addEventListener('load', function () {

    // Checking if Web3 has been injected by the browser (Mist/MetaMask)
    if (typeof web3 !== 'undefined') {
        // Use Mist/MetaMask's provider
        window.web3 = new Web3(web3.currentProvider);
    } else {

        document.getElementById('metamask').innerHTML = 'This Demo needs, <a href="https://metamask.io/">Meta Mask installed...</a>';
        console.log('Injected web3 Not Found!!!')
        // fallback - use your fallback strategy (local node / hosted node + in-dapp id mgmt / fail)
        window.web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));

        var provider = document.getElementById('provider_url').value;
        window.web3 = new Web3(new Web3.providers.HttpProvider(provider));
    }

    var opts = {
        angle: 0.1, // The span of the gauge arc
        lineWidth: 0.3, // The line thickness
        radiusScale: 1, // Relative radius
        pointer: {
            length: 0.58, // // Relative to gauge radius
            strokeWidth: 0.066, // The thickness
            color: '#757575' // Fill color
        },
        limitMax: false,     // If false, max value increases automatically if value > maxValue
        limitMin: false,     // If true, the min value of the gauge will be fixed
        colorStart: '#6F6EA0',   // Colors
        colorStop: '#9E9E9E',    // just experiment with them
        strokeColor: '#EEEEEE',  // to see which ones work best for you
        generateGradient: true,
        highDpiSupport: true,     // High resolution support

    };

    var target = document.getElementById('g1'); // your canvas element
    gauge = new Gauge(target).setOptions(opts); // create sexy gauge!
    gauge.maxValue = 300; // set max gauge value
    gauge.setMinValue(0);  // Prefer setter over gauge.minValue = 0
    gauge.animationSpeed = 1000; // set animation speed (32 is default value)
    gauge.set(15); // set actual value
    gauge.setTextField(document.getElementById('preview-text'));

    setInterval(function () {
        gauge.set(getRandomInt(0, 300));
    }, 2500);

    // Now you can start your app & access web3 freely:
    //startApp();

    doCalcContractFunctionCall();
})

/** Random integer  */
function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * This method gets invoked when document is ready
 */
function startApp() {

    // If the app is reconnected we should reset the watch
    doFilterStopWatching();
    doContractEventWatchStop();

    // Set the connect status on the app
    if (web3 && web3.isConnected()) {
        setData('connect_status', 'Connected', false);

        // Gets the version data and populates the result UI
        setWeb3Version();

        if (autoRetrieveFlag) doGetAccounts();

    } else {
        setData('connect_status', 'Not Connected', true);
    }

    // no action to be taken if this flag is OFF  
    // during development for convinience you may set autoRetrieveFlag=true
    if (!autoRetrieveFlag) return;



    // doConnect();
    // // doGetAccounts();
    doGetNodeStatus();

    // Compilation is available only for TestRPC
    // Geth 1.6 and above does not support compilation
    // MetaMask does not support compilation
    doGetCompilers();
}

/**
 * This method is called for connecting to the node
 * The Provider URL is provided in a Document element with the 
 * id = provider_url
 */


function doConnect() {

    // Get the provider URL
    var provider = document.getElementById('provider_url').value;
    var provider = document.getElementById('provider_url').value;
    window.web3 = new Web3(new Web3.providers.HttpProvider(provider));
    startApp();

}

/**
 * Get the version information for Web3
 */

function setWeb3Version() {

    var versionJson = {};

    // Asynchronous version
    web3.version.getNode(function (error, result) {
        if (error) setData('version_information', error, true);
        else {
            setData('version_information', result, false);

            if (result.toLowerCase().includes('metamask')) {
                nodeType = 'metamask';
            } else if (result.toLowerCase().includes('testrpc')) {
                nodeType = 'testrpc';
            } else {
                nodeType = 'geth';
            }


            // set up UI elements based on the node type
            setUIBasedOnNodeType();
        }
    });
}



/**
 * Uses the web3.net status to check if the client is listening and peer count
 */

function doGetNodeStatus() {

    // Asynch version
    web3.net.getListening(function (error, result) {
        if (error) setData('get_peer_count', error, true);
        else {
            // Since connected lets get the count
            web3.net.getPeerCount(function (error, result) {
                if (error) {
                    setData('get_peer_count', error, true);
                } else {
                    setData('get_peer_count', 'Peer Count: ' + result, (result == 0));
                }
            });
        }
    });
}

/**
 * Gets the accounts under the node
 * 
 */

function doGetAccounts() {
    // This is the synch call for getting the accounts
    // var accounts = web3.eth.accounts

    // Asynchronous call to get the accounts
    // result = [Array of accounts]
    // MetaMask returns 1 account in the array - that is the currently selected account
    web3.eth.getAccounts(function (error, result) {
        if (error) {
            setData('accounts_count', error, true);
        } else {
            accounts = result;
            setData('accounts_count', result.length, false);
            // You need to have at least 1 account to proceed
            if (result.length == 0) {
                if (nodeType == 'metamask') {
                    alert('Unlock MetaMask *and* click \'Get Accounts\'');
                }
                return;
            }

            // Remove the list items that may already be there
            removeAllChildItems('accounts_list');
            // Add the accounts as list items
            for (var i = 0; i < result.length; i++) {
                addAccountsToList('accounts_list', i, result[i])
            }

            var coinbase = web3.eth.coinbase;
            // trim it so as to fit in the window/UI
            if (coinbase) coinbase = coinbase.substring(0, 25) + '...'
            setData('coinbase', coinbase, false);
            // set the default accounts
            var defaultAccount = web3.eth.defaultAccount;
            if (!defaultAccount) {
                web3.eth.defaultAccount = result[0];
                defaultAccount = '[Undef]' + result[0];
            }

            defaultAccount = defaultAccount.substring(0, 25) + '...';
            setData('defaultAccount', defaultAccount, false);
        }
        // Get the balances of all accounts doGetBalances
        doGetBalances(accounts)

        // This populates the SELECT boxes with the accounts
        addAccountsToSelects(accounts);
    });
}

/**
 * Get the balances of all accounts.
 */
function doGetBalances(accounts) {

    // Remove the balances if they already exist
    removeAllChildItems('account_balances_list');

    // Add the balances as the list items
    for (var i = 0; i < accounts.length; i++) {

        // var bal = web3.eth.getBalance(accounts[i]);
        web3.eth.getBalance(accounts[i], web3.eth.defaultBlock, function (error, result) {
            // Convert the balance to ethers
            var bal = web3.fromWei(result, 'ether').toFixed(2);
            addAccountBalancesToList('account_balances_list', i, bal);
        });
    }
}

/**
 * This gets invoked for sending the transaction
 */

function doSendTransaction() {

    var transactionObject = createTransactionObjectJson();

    web3.eth.sendTransaction(transactionObject, function (error, result) {

        if (error) {
            setData('send_transaction_error_or_result', error, true);
        } else {
            setData('send_transaction_error_or_result', result, false);
            // set the link to ether scan
            var etherscanLinkA = document.getElementById('etherscan_io_tx_link');
            etherscanLinkA.href = createEtherscanIoUrl('tx', result);
            etherscanLinkA.innerHTML = 'etherscan.io'
            //console.log(etherscanLinkA)
        }
    });
}

/**
 * Unlocks the account
 * UNLOCK/LOCK not supported in TestRPC
 * Ignored in MetaMask
 */

function doUnlockAccount() {

    setData('lock_unlock_result', '...', true);
    var account = document.getElementById('select_to_unlock_account').value;
    var password = document.getElementById('unlock_account_password').value;

    // synchronous flavor
    // web3.personal.unlockAccount(account, password, duration)
    // web3.personal.unlockAccount(account, password)


    web3.personal.unlockAccount(account, password, function (error, result) {

        // console.log(error,result)
        if (error) {
            setData('lock_unlock_result', error, true);
        } else {
            // Result = True if unlocked, else false
            var str = account.substring(0, 20) + '...Unlocked';
            if (result) {
                setData('lock_unlock_result', str, false);
            } else {
                // This does not get called - since and error is returned for incorrect password :-)
                str = 'Incorrect Password???';
                setData('lock_unlock_result', str, true);
            }


        }
    });
}

/**
 * Lock the account
 */
function doLockAccount() {



    setData('lock_unlock_result', '...', true);
    var account = document.getElementById('select_to_unlock_account').value;
    //Synchronous flavor
    //web3.personal.lockAccount(account)

    web3.personal.lockAccount(account, function (error, result) {

        console.log(error, result)
        if (error) {
            setData('lock_unlock_result', error, true);
        } else {
            var str = account.substring(0, 20) + '...Locked';
            setData('lock_unlock_result', str, false);
        }
    });
}

/**
 * Gets the list of compilers
 */
function doGetCompilers() {



    web3.eth.getCompilers(function (error, result) {
        if (error) {
            setData('list_of_compilers', error, true);
        } else {
            // result has an array of compilers
            if (result.length == 0)
                setData('list_of_compilers', 'No Compilers!!!', true);
            else
                setData('list_of_compilers', result, false);
        }
    });
}

/**
 * Starting geth 1.6 - Solidity compilation is not allowed from
 * web3 JSON/RPC
 */

function doCompileSolidityContract() {


    var source = document.getElementById('sourcecode').value;

    console.log(flattenSource(source));

    web3.eth.compile.solidity(source, function (error, result) {

        if (error) {
            console.log(error);
            setData('compilation_result', error, true);
        } else {
            // This is an issue seen only on windows - solc compile binary - ignore
            result = compileResultWindowsHack(result);
            console.log('Compilation Result=', JSON.stringify(result));
            var contract_1 = '';
            var code_1 = '';
            var abi_1 = '';
            for (var prop in result) {
                contract_1 = prop;
                code_1 = result[prop].code;
                if (!code_1) {
                    // Test RPC returns code in result.code
                    code_1 = result.code;
                }
                if (result[prop].info) {
                    abi_1 = result[prop].info.abiDefinition;
                } else {
                    // Test RPC does not have the contracts :) in result
                    abi_1 = result.info.abiDefinition;
                }
                break;
            }
            // Populate the UI elements
            setData('compilation_result', 'Contract#1: ' + contract_1, false);
            document.getElementById('compiled_bytecode').value = code_1;
            document.getElementById('compiled_abidefinition').value = JSON.stringify(abi_1);

        }
    });
}




/**
 * Deploys the contract - ASYNCH
 */

function doDeployContract() {
    // Reset the deployment results UI
    resetDeploymentResultUI();

    var abiDefinitionString = document.getElementById('compiled_abidefinition').value;
    var abiDefinition = JSON.parse(abiDefinitionString);

    var bytecode = document.getElementById('compiled_bytecode').value;

    // 1. Create the contract object
    var contract = web3.eth.contract(abiDefinition);

    // Get the estimated gas
    var gas = document.getElementById('deployment_estimatedgas').value;

    // 2. Create the params for deployment - all other params are optional, uses default
    var params = {
        from: web3.eth.coinbase,
        data: bytecode,
        gas: gas
    }

    // 3. This is where the contract gets deployed
    // Callback method gets called *2* 
    // First time : Result = Txn Hash
    // Second time: Result = Contract Address
    var constructor_param = 10;

    contract.new(constructor_param, params, function (error, result) {

        if (error) {
            setData('contracttransactionhash', 'Deployment Failed: ' + error, true);
        } else {
            console.log('RECV:', result)
            if (result.address) {
                document.getElementById('contractaddress').value = result.address;
                setEtherscanIoLink('contractaddress_link', 'address', result.address);
            } else {
                // gets set in the first call
                setData('contracttransactionhash', result.transactionHash, false);
                setEtherscanIoLink('contracttransactionhash_link', 'tx', result.transactionHash);
            }
        }
    });
}

/**
 * Deploys the contract - Synchronous
 * Function not in use from UI. Created to show how once can use the synch API
 * contract.new
 */

function doDeployContractSynchronous() {

    var abiDefinitionString = document.getElementById('compiled_abidefinition').value;
    var abiDefinition = JSON.parse(abiDefinitionString);

    var bytecode = document.getElementById('compiled_bytecode').value;

    // 1. Create the contract object
    var contract = web3.eth.contract(abiDefinition);

    // Get the estimated gas
    var gas = document.getElementById('deployment_estimatedgas').value;

    // 2. Create the params for deployment - all other params are optional, uses default
    var params = {
        from: web3.eth.coinbase,
        data: bytecode,
        gas: gas
    }

    var contractData = contract.new.getData(10, { 'data': bytecode });
    console.log('Contract Data=', contractData);
    // call send transaction and then call getTransactionReceipt
    params.data = contractData
    var transactionHash = web3.eth.sendTransaction(params)
    console.log('TxnHash=', transactionHash);
    web3.eth.getTransactionReceipt(transactionHash, function (error, result) {
        if (error) console.log('SENDTran Error=', error)
        else if (error) console.log('SENDTran Hash=', result);
    });

    return
}

// Utility method for creating the contract instance
function createContractInstance(addr) {
    var abiDefinitionString = contract_abidefinition;
    var abiDefinition = JSON.parse(abiDefinitionString);

    // Instance uses the definition to create the function

    var contract = web3.eth.contract(abiDefinition);

    // THIS IS AN EXAMPLE - How to create a deploy using the contract
    // var instance = contract.new(constructor_params, {from:coinbase, gas:10000})
    // Use the next for manual deployment using the data generated
    // var contractData = contract.new.getData(constructor_params, {from:coinbase, gas:10000});

    var address = contract_address;

    if (!address) address = document.getElementById('contractaddress').value;

    // Instance needs the address

    var instance = contract.at(address);

    return instance;
}


/**
 * This invokes the contract function
 * locally on the node with no state change propagation
 */
function doContractFunctionCall() {
    // This leads to the invocation of the method locally
    var instance = createContractInstance();

    var funcName = document.getElementById('contract_select_function').value;

    if (funcName === 'setNum') {
        var parameterValue = document.getElementById('setnum_parameter').value;

        // MetaMask does not allow synchronous call to 'call' for non-constant function
        // Change this to asynchronous :)
        var value = instance.setNum.call(parameterValue);

        setExecuteResultUI('Call', funcName, parameterValue, value, '', false);
    } else {

        instance.getNum.call({}, web3.eth.defaultBlock, function (error, result) {
            setExecuteResultUI('Call', funcName, '', result, '', false);
        });


    }
}


/**
 * This invokes the contract function
 * locally on the node with no state change propagation
 */
function doCalcContractFunctionCall() {
    // This leads to the invocation of the method locally
    var instance = createContractInstance();
    var funcName = 'getBalance';

    instance.getBalance.call({}, web3.eth.defaultBlock, function (error, result) {
        setCalcExecuteResultUI('Call', funcName, '', result, '', false);
    });

    instance.getLastTransaction.call({}, web3.eth.defaultBlock, function (error, result) {
        if(error) console.log(error);
        else
            setTransactionExecuteResultUI('0', result);
    });

    instance.getLast1Transaction.call({}, web3.eth.defaultBlock, function (error, result) {
        if(error) console.log(error);
        else
            setTransactionExecuteResultUI('1', result);
    });

    instance.getLast2Transaction.call({}, web3.eth.defaultBlock, function (error, result) {
        if(error) console.log(error);
        else
            setTransactionExecuteResultUI('2', result);
    });

    instance.getLast3Transaction.call({}, web3.eth.defaultBlock, function (error, result) {
        if(error) console.log(error);
        else
            setTransactionExecuteResultUI('3', result);
    });
    
    instance.getLast4Transaction.call({}, web3.eth.defaultBlock, function (error, result) {
        if(error) console.log(error);
        else
            setTransactionExecuteResultUI('4', result);
    });

    /*
        // Create the transaction object
        var txnObject = {
            from: web3.eth.coinbase
        }
    
            // getNum with sendTransaction
            instance.getNum.sendTransaction(txnObject, function (error, result) {
    
                //alert(result);
                console.log('RECVED>>', error, result);
                if (error) {
                    setCalcExecuteResultUI('Send Transaction:   ', funcName, 'asdasd', error, 'asdsad', true);
                } else {
                    setCalcExecuteResultUI('Send Transaction:   ', funcName, 'asdsad', result, result, false);
                }
            });
    */

}



/**
 * This invokes the contract function
 * locally on the node with no state change propagation
 */
function doSendCalcTransaction(amount) {
    // This leads to the invocation of the method locally
    var instance = createContractInstance();
    var funcName = 'recharge';

    document.getElementById('invoke_return_value').innerHTML = 'Please wait...';

    // Create the transaction object
    var txnObject = {
        from: web3.eth.coinbase
    }

    var donar = document.getElementById('donar').value;
    if(donar=='') donar = 'Humble Donation';

    // getNum with sendTransaction
    instance.recharge.sendTransaction(amount, donar, txnObject, function (error, result) {

        //alert(result);
        console.log('RECVED>>', error, result);
        if (error) {
            setCalcExecuteResultUI('Send Transaction:   ', funcName, '', error, '', true);
        } else {
            setCalcExecuteResultUI('Send Transaction:   ', funcName, '', '<img src="./images/progress.gif">Submitted: pls wait</img>', result, false);
        }
    });

    var myEvent = instance.EventRechargeDone();
    myEvent.watch(function(error, result){
        doCalcContractFunctionCall();
    });

    // window.setTimeout(function () {
    //     doCalcContractFunctionCall();
    // }, 30000);
}

/**
 * Sets the Result UI components for the Execute call
 */
function setCalcExecuteResultUI(callType, functionName, parameter, return_value, txHash, error) {

    var detail = callType + ':' + functionName + '(' + parameter + ')';
    if (error) detail += ' FAILED ' + return_value;
    else detail += 'Successful';

    //setData('invoke_details',detail,(error));
    setData('invoke_return_value', return_value, (error));
    var txHash_display = txHash;
    if (txHash) {
        txHash_display = 'Transaction Hash: ' + txHash
    }
    setData('invoke_contracttransactionhash', txHash_display, false);
    setEtherscanIoLink('invoke_contracttransactionhash_link', 'tx', txHash);
}

function setTransactionExecuteResultUI(id, result) {
    
    var d = new Date(result[2].toNumber()*1000);
    setTableData('name'+id, result[1]);
    setTableData('amt'+id, result[0]);
    setTableData('time'+id, d.toLocaleString() );
}

function setTableData(docElementId, html) {
    document.getElementById(docElementId).innerHTML = html;
}


/**
 * send Transaction costs Gas. State changes are recorded on the chain.
 */
function doContractSendCall() {
    // creating the cntract instance
    var instance = createContractInstance();
    // read the ui elements
    var estimatedGas = document.getElementById('contract_execute_estimatedgas').value;
    var parameterValue = document.getElementById('setnum_parameter').value;
    var funcName = document.getElementById('contract_select_function').value;
    //value NOT used as the contract function needs to be modified with "payable" modifier
    //var value = document.getElementById('invocation_send_value_in_ether').value;
    //value = web3.toWei(value,'ether');

    // Create the transaction object
    var txnObject = {
        from: web3.eth.coinbase,
        gas: estimatedGas
    }

    if (funcName === 'setNum') {
        // setNum with sendTransaction
        instance.setNum.sendTransaction(parameterValue, txnObject, function (error, result) {

            console.log('RECVED>>', error, result);
            if (error) {
                setExecuteResultUI('Send Transaction:   ', funcName, '', error, '', true);
            } else {
                setExecuteResultUI('Send Transaction:   ', funcName, parameterValue, result, result, false);
            }
        });
    } else {
        // getNum with sendTransaction
        instance.getNum.sendTransaction(txnObject, function (error, result) {

            console.log('RECVED>>', error, result);
            if (error) {
                setExecuteResultUI('Send Transaction:   ', funcName, '', error, '', true);
            } else {
                setExecuteResultUI('Send Transaction:   ', funcName, '', result, result, false);
            }
        });
    }
}

/**
 * Starts the filter watch for events with options specified by the user
 */


function doFilterWatchStart() {
    //1. Stop the wtach if its already ON
    doFilterStopWatching();
    //2. Reset the UI
    setData('watch_event_count', '0', false);

    //3. Create the filter option
    var options = generateFilterOptions();
    console.log('FILTER Watch Options:', JSON.stringify(options));

    //4. Set the applied watch filter UI Input box
    document.getElementById('applied_watch_filter').value = JSON.stringify(options);

    //5. Create instance of the filter
    filterWatch = web3.eth.filter(options);

    //6. Now start watching
    filterWatch.watch(function (error, result) {
        if (error) {
            console.error('Filter Watch Error: ', error);
        } else {
            filterEventCounter++;
            // Update the UI for the counter
            setData('watch_event_count', filterEventCounter, false);

            // Updates the UI with received event
            addEventListItem('watch_events_list', result, 5);
        }
    });
}

/**
 * Stop watching for events
 */

function doFilterStopWatching() {

    // 1. Stop watching if watching iactive
    if (filterWatch) {
        filterWatch.stopWatching();
        filterWatch = undefined;
    }
    // 2. Reset the UI
    setData('watch_event_count', 'Not Watching', true);
    document.getElementById('applied_watch_filter').value = '';

    // 3. Remove all of the past events from the list
    clearList('watch_events_list');

    // 4. reset the counter
    filterEventCounter = 0;
}

/**
 * Get the logs for the specified filter
 * Testnet sample contract address: 
 */

function doFilterGetLogs() {

    // 1. Clear the list
    clearList('get_logs_list');

    // 2. Create the filter option
    var options = generateFilterOptions();
    console.log('FILTER Get Options:', JSON.stringify(options));

    // 3. Set the applied watch filter UI Input box
    document.getElementById('applied_log_filter').value = JSON.stringify(options);

    // 4. Create the instance of the filter
    var filterGet = web3.eth.filter(options);

    // 5. Invoke get on filter with the callback function
    filterGet.get(function (error, result) {
        if (error) {
            console.log('GET Error:', error);
            setData('get_log_count', error, true);
        } else {
            // result = array of events
            // Update UI with the data received as an array of events
            setData('get_log_count', result.length, false);
            for (var i = 0; i < result.length; i++) {
                //console.log("Event.watch="+JSON.stringify(result[i]))
                addEventListItem('get_logs_list', result[i], 50);
            }
        }
    });
}

/**
 * To start the event watching using the contract object
 */

function doContractEventWatchStart() {

    if (contractEvent) {
        doContractEventWatchStop();
    }

    // Reset the UI
    setData('watch_contract_instance_event_count', '0', false);

    contractEvent = createContractEventInstance();

    contractEvent.watch(function (error, result) {
        if (error) {
            console.error('Contract Event Error');
        } else {

            //    console.log("Event.watch="+JSON.stringify(result))
            // increment the count watch_instance_event_count
            contractEventCounter++;
            setData('watch_contract_instance_event_count', contractEventCounter, false);

            addEventListItem('watch_contract_events_list', result, 5);
        }
    });
}


/**
 * To stop the event watching using the contract object
 */

function doContractEventWatchStop() {

    if (contractEvent) {
        contractEvent.stopWatching();
        contractEvent = undefined;
    }
    contractEventCounter = 0;
    clearList('watch_contract_events_list');
    setData('watch_contract_instance_event_count', '---', true);
}

/**
 * Gets the logs for the specific contract instance
 */

function doContractEventGet() {

    clearList('get_contract_instance_logs_list');
    setData('get_contract_instance_log_count', '---', true);
    var event = createContractEventInstance();
    event.get(function (error, result) {
        if (error) {
            setData('get_contract_instance_log_count', error, true);
        } else {
            setData('get_contract_instance_log_count', result.length, false);
            for (var i = 0; i < result.length; i++) {
                addEventListItem('get_contract_instance_logs_list', result[i], 50);
            }
        }
    });
}

/**
 * Utility method for creating an instance of the event
 */
function createContractEventInstance() {
    var contractAddress = document.getElementById('contract_instance_address').value

    var contractInstance = createContractInstance(contractAddress);

    // geth the indexed data values JSON
    var indexedEventValues = document.getElementById('indexed_event_values').value
    indexedEventValues = JSON.parse(indexedEventValues)

    var additionalFilterOptions = document.getElementById('additional_filter_event_values').value;
    additionalFilterOptions = JSON.parse(additionalFilterOptions);

    return contractInstance.NumberSetEvent(indexedEventValues, additionalFilterOptions);
}
